### ISSUE TITLE
Add hardware wallet support

### ISSUE THREAD

**Issue by rmeissner** [5afe/safe-cli#29]
It would be nice if I could use the safe-cli with my ledger or trezor

--- Edit By Uxío ---

This task will be replaced by:

- https://github.com/5afe/safe-cli/issues/269
- https://github.com/5afe/safe-cli/issues/270

**Comment by fubuloubu** [comment]
Probably not possible until https://github.com/ethereum/web3.py/issues/847 is added

**Comment by Uxio0** [comment]
> Probably not possible until [ethereum/web3.py#847](https://github.com/ethereum/web3.py/issues/847) is added

It's not completely necessary, but it would be awesome if they support it, then it would be really easy to add support

**Comment by AdamSHurwitz** [comment]
Does this mean that if a user initiates a send transaction using the CLI, they will not be able to sign the transaction with a hardware wallet?

Or can a user still sign with a hardware wallet, it's just the CLI won't provide any feedback on the signature, thus requiring the user to check on Etherscan?

**Comment by Uxio0** [comment]
> Does this mean that if a user initiates a send transaction using the CLI, they will not be able to sign the transaction with a hardware wallet?

That's right, Cli does not have integration with hardware wallets, but if you use `--tx-service` in a network supported (`mainnet` or `rinkeby`) you will be able to sign the transaction with a hardware wallet in the web ui.

**Comment by AdamSHurwitz** [comment]
Thank you @Uxio0! To ensure I understand, when initiating a send transaction, the `--tx-service` command line parameter must be provided with either `mainnet` or `rinkeby`.

Taking the demo transaction as an example, in order to sign the tx with a hardware wallet in production, the command would look like this:

`send_ether 0x5aC255889882aCd3da2aA939679E3f3d4cea221e 123  --tx-service mainnet`

Then, a browser will launch with a Web UI or does the user need to run the [Safe React UI][1] to interact with the command?

[1]: https://github.com/gnosis/safe-react

**Comment by Uxio0** [comment]
You got it right until this point:

`Then, a browser will launch with a Web UI or does the user need to run the Safe React UI in order to interact with the command`

You need to open the browser yourself and go to the Safe React UI.

One important note: You need at least one valid owner (key) imported on the Safe-cli, as Web UI only shows transactions with at least one signature.

**Comment by AdamSHurwitz** [comment]
Does this mean if a user has all hardware wallets for signing it is currently impossible to confirm transactions with the CLI tool?

What is the best approach for an all hardware wallet configuration recovery?
- Download a [past release][1], presuming the smart contracts are still deployed.
- If the smart contracts are not deployed, deploying [GnosisSafe.sol][2] and calling the methods to sign each hardware wallet directly with an IDE like Remix.

[1]: https://github.com/gnosis/safe-react/releases
[2]: https://github.com/gnosis/safe-contracts/blob/development/contracts/GnosisSafe.sol

**Comment by RomanHiden** [comment]
I must say this is what I was  looking for. besides this would be nice to have integration with eth-brownie framework. it already connects with clef to hw wallet. I just need safe operations available

**Comment by danicuki** [comment]
👍

**Comment by chrdevmar** [comment]
> You are welcome! You got it right until this point:
> 
> > Then, a browser will launch with a Web UI or does the user need to run the Safe React UI in order to interact with the command
> 
> You need to open the browser yourself and go to the Safe React UI.
> 
> One important note: You need at least one valid owner (key) imported on the Safe-cli, as Web UI only shows transactions with at least one signature.

Does the web UI only show pending transactions with signatures from one of the owners or can it be signed by any key? I ask this because I would like to generate a transaction from the CLI but the owner addresses are all hardware wallets. If I generate a message via the cli with some random private key, will it show in the web UI and have `0/n confirmations`?

**Comment by Uxio0** [comment]
> Does the web UI only show pending transactions with signatures from one of the owners or can it be signed by any key? I ask this because I would like to generate a transaction from the CLI but the owner addresses are all hardware wallets. If I generate a message via the cli with some random private key, will it show in the web UI and have `0/n confirmations`?

For transactions to show in the UI they need to be signed by at least one owner or delegate

**Comment by Uxio0** [comment]
Superseded by #269 and #270
